### ISSUE TITLE
I was bored and made an Userscript

### ISSUE THREAD

**Issue by henrik9999** [goldbattle/MangadexRecomendations#2]
Hi, so basically i just wanted to say that i made an Userscript for this which can be used on MangaDex to view the recommendations. Here is the link:
https://greasyfork.org/en/scripts/415324-mangadex-recommendations

**Comment by goldbattle** [comment]
Looks great, thanks for being interested.
You might also want to checkout this chrome web extension that I made a while back:
https://chrome.google.com/webstore/detail/mangadex-similar-manga/ghjofcifjnbpgfjbbnbeeipjlhnmbefl?hl=en

I have meant to push the code to this repo, but have not found the time.

**Comment by henrik9999** [comment]
> Looks great, thanks for being interested.
> You might also want to checkout this chrome web extension that I made a while back:
> https://chrome.google.com/webstore/detail/mangadex-similar-manga/ghjofcifjnbpgfjbbnbeeipjlhnmbefl?hl=en
> 
> I have meant to push the code to this repo, but have not found the time.

Haha cool i tried doing it without having a need to request data from every manga tho
